Signup/signin flow
sandboxnu/knowyouroptions pull request #7
Opened 2021-12-01 23:19 UTC by aislinblack

2021-12-08 21:16 UTC, stefan-philip requested changes
I'm getting HTTP errors in the console when signing up/signing in

2021-12-08 21:23 UTC, aislinblack commented
> I'm getting HTTP errors in the console when signing up/signing in

It would be helpful if you could provide a screenshot of the errors, also, are you trying to use it on vercel bc that won’t work? You need to run the front and backend manually

2021-12-09 00:26 UTC, dillydally414 commented
I know there were console errors occurring when there was an issue with signin/signup, but I couldn't find a way to fully remove them, only changing the form of the popup to a more user friendly toast instead of the automatically generated error popup

2022-03-06 22:06 UTC, stefan-philip approved these changes

2022-03-06 22:07 UTC, merged